project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - activities.qmd
    - current_research.qmd

website:
  cookie-consent:
    type: implied
    style: simple
    palette: dark

  back-to-top-navigation: True
  title: Mathew Cieśla
  navbar:
    background: "#333533"
    foreground: "#ECF0F1"#
    search: false
    left:
      - text: "home"
        href: index.qmd
      - text: "activities"
        href: activities.qmd
      - text: "research"
        href: current_research.qmd
      - text: "more"
        menu:
          - text: "researchgate"
            href: "https://www.researchgate.net/profile/Mathew-Ciesla"
            target: _blank
          - text: "orcid"
            href: "https://orcid.org/0000-0003-0803-2085"
            target: _blank
          - text: "twitter"
            href: "https://twitter.com/m_ciesla"
            target: _blank
  
format:
  html:
    theme: darkly
    css: styles.css
    toc: false
    color: "white"
    backgroundcolor: "#333533"
    
  

editor: visual

