project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - activities.qmd
    - current_research.qmd

website:
  cookie-consent:
    type: implied
    style: simple
    palette: dark

  back-to-top-navigation: True
  title: Mathew Cieśla
  navbar:
    background: "#202020"
    foreground: "#ECF0F1"#
    search: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Activities"
        href: activities.qmd
      - text: "Research"
        href: current_research.qmd
  
format:
  html:
    theme: darkly
    css: styles.css
    toc: false
    color: "white"
    backgroundcolor: "#202020"
    
  

editor: visual

