project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - activities.qmd
    - current_research.qmd

website:
  cookie-consent:
    type: implied
    style: simple
    palette: dark

  back-to-top-navigation: True
  title: Mathew Cieśla
  navbar:
    background: "#333533"
    foreground: "#ECF0F1"#
    search: false
    left:
      - text: "home"
        href: index.qmd
      - text: "activities"
        href: activities.qmd
      - text: "research"
        href: current_research.qmd
      - text: "more"
        menu:
          - text: "ResearchGate"
            href: "https://www.researchgate.net/profile/Mathew-Ciesla"
            target: _blank
          - text: "Bluesky"
            href: "https://bsky.app/profile/mciesla.bsky.social"
            target: _blank
          - text: "Linkedin"
            href: "https://www.linkedin.com/in/mathew-cieśla-8b57642b5/"
            target: _blank
          - text: "Northumbria University"
            href: "https://researchportal.northumbria.ac.uk/en/persons/mathew-cieśla"
            target: _blank

  
format:
  html:
    theme: darkly
    css: styles.css
    toc: false
    color: "white"
    backgroundcolor: "#333533"
    
  

editor: visual

