---
title: ""
---

# Activities

## <font size = "5">Publications</font>

<font size = "3">

-   Cieśla, M., Kapnoula, E. C., Pozdniakov, M., Gruszecka, J., Jankowiak, K. (<a href = "https://www.cambridge.org/core/journals/bilingualism-language-and-cognition/article/impact-of-orthography-versus-images-on-foreign-language-learning-evidence-from-behavioral-and-neural-markers/3BCD137A3C88327937628A9894234D32" target = "_blank">2025</a>). The Impact of Orthography Versus Images on Foreign Language Learning: Evidence From Behavioral and Neural Markers. *Bilingualism: Language and Cognition*

-   Morett, L., Cieśla, M., Bray, M., Hughes-Berheim, S., Emmorey, K., (<a href = "https://www.cambridge.org/core/journals/studies-in-second-language-acquisition/article/feeling-signs-motor-encoding-enhances-sign-language-learning-in-hearing-adults/007AF08B353F15DD7E8298B92001D05D" target = "_blank">2024</a>). Feeling signs: Motor encoding enhances sign language learning in hearing adults. *Studies in Second Language Acquisition*

</font>

## <font size = "5">Preregistrations</font>

<font size = "3">

-   Cieśla, M., Blythe, H., Kempe, V., Williams, G.P. (<a href = "https://doi.org/10.17605/OSF.IO/JW645" target = "_blank">2025</a>). Dialect Effects on Contrastive vs. Mainstream Word Reading in Dialect-Speaking Adults. *OSF*

-   Cieśla, M., Blythe, H., Kempe, V., Grugan, M., Myachykov, A., Williams, G.P. (<a href = "https://doi.org/10.17605/OSF.IO/G7TQE" target = "_blank">2024</a>). Dialect Density. *OSF*

</font>

## <font size = "5">Conferences / Talks</font>

<font size = "3">

-   Dept. of Psychology Postgraduate Research Conference (2025), Newcastle, UK; *organiser, co-chair, talk*

-   Eurasian Congress of Linguists (2024), online; *talk*

-   Psychonomics (2024), New York, USA; *poster*

-   Auditory Processing and Cognition Annual Meeting (2024), New York, USA; *talk*

-   Architectures and Mechanisms for Language Processing (2024), Edinburgh, UK; *poster*

-   Psychonomics (2023), San Francisco, USA; *poster*

-   European Society of Cognitive Psychology (2023), Porto, Portugal; *poster*

-   Architectures and Mechanisms for Language Processing (2023), Donostia-San Sebastian, Spain; *poster*

-   Young Linguists Meeting Poznań (2023), Poznań, Poland; *workshop*

</font>

## <font size = "5">Study Visits</font>

<font size = "3">

-   Faculty of English, Adam Mickiewicz University (2022-2023), Poznań, Poland

-   Basque Center on Cognition, Brain and Language, Spoken Language Research Group (2023), Donostia-San Sebastian, Spain

</font>

## <font size = "5">Education Visits</font>

<font size="3">

-   Jülich Research Center, Institute for Neuroscience and Medicine (2019), Jülich, Germany; *Neuroimaging internship with Dr. Paola Mengotti*

-   University of Cologne (2019), Cologne, Germany; *Spring School: Language and Music in Cognition*

</font>

## <font size = "5">Peer Reviewing</font>

<font size = "3">

-   Bilingualism: Language and Cognition

-   Forum for Linguistics Studies

</font>

## <font size = "5">Teaching / Demonstrating Experience </font>

<font size="3">

-   Psychometrics and Individual Differences

-   Advanced Experimental Methods

-   Quantitative Statistical Methods

-   Qualitative Research Methods

</font>
