---
title: ""
---

# Research

## <font size = "5">General Research Overview</font>

<font size = "3">Mathew's research largely focuses on aspects of lexico-semantic development in late, second language learners utilising electroencephalography (EEG) and event-related potential (ERP) techniques. More recently and as part of his Ph.D. work, Mathew has begun research involving bidialectals (those who speak and are exposed to two or more dialects), and the effects of dialect on literacy and reading in children and adults. </font>

## <font size = "5">Current Projects</font>

-   <font size = "3"><b>SETA</b> - </font><font size = "3">Dialect effects on contrastive vs. mainstream word reading in dialect-speaking adults </font><br><font size = "2">(This project is available on the <a href = "https://osf.io/jw645" target = "_blank">OSF</a>)</font>

-   <font size = "3"><b>Decoding Dialect Density</b> - </font><font size = "3">Psychometric development for the measurement of dialect density. </font><br><font size = "2">(This project is available on the <a href = "https://osf.io/gwe3k/" target = "_blank">OSF</a>)</font>

## <font size = "5">Past Research</font>

-   <font size = "3"> <b>FLACON</b> - </font><font size = "3">Exploring the effects of image and orthographic referents on the early stages of late, second language acquisition. </font><font size = "2"> (read the article <a href = "https://www.cambridge.org/core/journals/bilingualism-language-and-cognition/article/impact-of-orthography-versus-images-on-foreign-language-learning-evidence-from-behavioral-and-neural-markers/3BCD137A3C88327937628A9894234D32" target = "_blank">here</a>)</font>

-   <font size = "3"><b>M2L2</b> - </font><font size = "3"> Effects of motor encoding on sign language acquisition in hearing adults. </font><font size = "2">(read the article <a href = "https://www.cambridge.org/core/journals/studies-in-second-language-acquisition/article/feeling-signs-motor-encoding-enhances-sign-language-learning-in-hearing-adults/007AF08B353F15DD7E8298B92001D05D" target = "_blank">here</a>) </font>
