---
title: ""
---

# Activities

## <font size = "4">Publications</font>

<font size = "2" font color=black>

-   Cieśla, M., Jankowiak, K., Pozdniakov, M., Gruszecka, J., Kapnoula, E. (in prep.). Neural markers of initial foreign language learning: Comparing orthography- and image-based inputs.

-   Morett, L., Cieśla, M., Hughes-Berheim, S., Emmorey, K., (submitted). Feeling signs: Motor input enhances sign language learning in hearing adults. *Studies in Second Language Acquisition*

</font>

## <font size = "4">Conferences</font>

<font size = "2" font color = "black">

-   Psychonomics (2023), San Francisco, California; *Poster*

-   European Society of Cognitive Psychology (ESCOP 2023), Porto, Portugal; <a href = "https://www.researchgate.net/publication/374551543_Comparing_L2_Word_Learning_Using_Orthographic_vs_Image_Referents" target = "_blank">*Poster*</a>

-   Architectures and Mechanisms for Language Processing (AMLaP 2023), San Sebastian, Spain; <a href = "https://www.researchgate.net/publication/374551543_Comparing_L2_Word_Learning_Using_Orthographic_vs_Image_Referents" target = "_blank">*Poster*</a>

-   Young Linguists Meeting Poznań (2023), Poznań, Poland; *Workshop & Thematic Session*

-   Alabama Speech Language Pathologist Informational Seminar (2020), Tuscaloosa, Alabama; *Presentation*

-   University of Alabama URCA Conference (2019), Tuscaloosa, Alabama; *Presentation*

</font>

## <font size = "4">Study Visits</font>

<font size = "2" font color = "black">

-   Faculty of English, Adam Mickiewicz University (2022-2023), Poznań, Poland

-   Basque Center on Cognition, Brain and Language, Spoken Language Research Group (2023), San Sebastian, Spain

</font>

## <font size = "4">Education Visits</font>

<font size="2" font color="black">

-   Jülich Research Center, Institute for Neuroscience and Medicine (2019), Jülich, Germany; *Neuroimaging internship with Dr. Paola Mengotti*

-   University of Cologne (2019), Cologne, Germany; *Spring School: Language and Music in Cognition*

</font>
